platform :ios do

  lane :lint do
    swiftlint(
      mode: :lint,
      path: "iosApp/iosApp",
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  private_lane :build_mcs do |options|
    build_app(
      project: "iosApp/iosApp.xcodeproj",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: true,
      skip_codesigning: true
    )
  end

  lane :build do
    lint()
    build_mcs(scheme: "iosApp")
  end

end